### ISSUE TITLE
Query Line-Rectangle Intersection with maprect() and queryset()

### ISSUE THREAD

**Issue by TheBlune** [dengwirda/aabb-tree#1]
Hey dengwirda,

thanks for uploading this great and really fast tool. It is already a tremendous help for me. 
I am trying to detect as fast as possible if there is a collision between a point-to-point line and the Rectangle-tree. How would I initiate your "fast" aabb-indexed variant from the demo? 

As I understand your demo, maprect() just computes point-rectangle intersections, right?

Thanks for any help.

**Comment by dengwirda** [comment]
Actually, I think 'maprect' may be what you're looking for here -- this routine will 'map' a set of rectangles onto an aabb-tree, building the indexing structure needed to do fast intersection tests.

If, say, you wanted to detect intersections between a set of lines and a set of objects, you could build a tree for the objects, form the bounding rectangles for the lines, and then use 'maprect' to build an index between the rectangles (associated with the lines) and the objects in the tree.

I do something like this to detect intersections between collections of lines here:

    https://github.com/dengwirda/mesh2d/tree/master/aabb-tree

**Comment by TheBlune** [comment]
Hey, 

I implemented my own solution and it works. So I am closing this issue. 

But just out of interest: 
Could you please explain to me what maprect actually does? I am having trouble understanding your code. What do you mean by "mapping" a rectangle onto a tree?

**Comment by dengwirda** [comment]
`maprect()` returns a structure that represents the 'intersection' between a set of rectangles and a given `aabb-tree`. Both the `tree-to-rectangle` and `rectangle-to-tree` maps can be generated, although typically only the first is needed. Both maps are 'arrays of lists'. 

In the case of the `tree-to-rectangle` map `TM`, the `k-th` entry is a list of rectangles that intersect with a given node in the tree. `TM.II[k]` is the tree-node index and `TM.LL[k]` is the list of rectangle indexes that intersect.

The overall aim here is spatial locality. If you want to compute the intersection between two collections of objects `(A,B)` you can: (1) build a tree for the objects in `A`, (2) use `maprect()` to 'map' the objects in `B` onto the tree, (3) use the mapping to compute the actual item-by-item intersections in a 'spatially local' sense.

To compute (3) efficiently, one could iterate over the `tree-to-rectangle` mapping. For the `k-th` entry in the map, item-by-item intersections should be computed between the objects (from collection `A`) associated with the tree node `TM.II[k]` and the list of objects (from collection `B`) that intersect with the node, i.e. `TM.LL[k]`.

**Comment by TheBlune** [comment]
Thanks for the explanation! :)
I will definitely try that out some time. 

Currently I check The Boxes for intersection beginning at the highest level. If an intersection is found, I continue with all the boxes that are inside the specific Box until I reach a specified level of resolution and can Confirm a collision. In my head this method seems to be effective, but I will test it against your ready-to-use solution later.
