### ISSUE TITLE
AABB-Tree construction issue for a simple box

### ISSUE THREAD

**Issue by TheBlune** [dengwirda/aabb-tree#2]
Hey dengwirda,

I found that the computed AABB-Tree of a simple 3D Box is faulty. Your Toolbox generates a big bounding box with two very thin child-boxes that do not describe the whole box. So iteration over different levels of the tree does not produce the correct results. 

Here is the .xx Table for the tree:
![image](https://user-images.githubusercontent.com/1479817/33942360-f9197a52-e015-11e7-842e-158b1fea7fa9.png)

Did I miss something or is this really a bug? 

Thanks for any help :)

**Comment by dengwirda** [comment]
I couldn't reproduce this issue - can you post the code you're using?

**Comment by TheBlune** [comment]
Heres an example: I manually create a 3D-Box with 6 faces and let your code do the magic:

objXmax = 1;
objYmax = 1;
objZmax = 1;
objXmin = 0;
objYmin = 0;
objZmin = 0;

pp = [objXmax,objYmax,objZmax;...
     objXmax,objYmin,objZmax;...
     objXmax,objYmax,objZmin;...
     objXmax,objYmin,objZmin;...
     objXmin,objYmax,objZmax;...
     objXmin,objYmin,objZmax;...
     objXmin,objYmax,objZmin;...
     objXmin,objYmin,objZmin;...
     ];
tt = [1,2,4,3;5,6,8,7;1,3,7,5;1,2,6,5;2,4,8,6;3,4,8,7];

bi = pp(tt(:,1),:); bj = pp(tt(:,1),:);
for ii = 2 : size(tt,2)    
    bi = min(bi,pp(tt(:,ii),:)) ;
    bj = max(bj,pp(tt(:,ii),:)) ;
end

tr = maketree([bi,bj])`

Prior to this I took a CAD-stl model with triangle-faces (12 Faces per Cube). This initially produced the error. But the code above does this as well.

Edit: 
Heres the resulting .xx Table:
![image](https://user-images.githubusercontent.com/1479817/34037799-634a8b08-e18a-11e7-9175-9d173c039f69.png)

**Comment by dengwirda** [comment]
This appears to define a surface mesh of a cube, where the `AABB`'s passed to `maketree()` are associated with each of the cube faces.

In this case, the tree decomposes the surface of the object, not its volume. The code looks to be doing what I'd expect.

**Comment by TheBlune** [comment]
Oh, I must have misunderstood your documentation then. It still seems strange, that your code decomposes the 6 surfaces only into two Subsurfaces. Shouldn't they be all six? 

I want to define an arbitrary object (like a box) and make a full AABB-Tree for Collision detection like in your demo2. 
Aren't you also using only Vertices and faces for the AABB-Construction there? What am I misssing?

Merry Christmas and thanks for your help.

**Comment by dengwirda** [comment]
Typically, it's more efficient for the tree to provide a 'coarse' representation of the collection rather than a 1:1 sampling, with each node in the tree containing multiple objects rather than individual items. By default, nodes will be split if they contain more than 32 items. 

It's not always easy / possible to decompose arbitrary collections of objects into 1:1 subdivisions, so it's not necessarily a good idea to assume that you can ensure there's only one item per tree-node.

**Comment by TheBlune** [comment]
I also wouldn't assume that a tree node represents only one item. But I understood that all sub-nodes of a tree-node contain all items of this node (only on a higher detail because there are more boxes to represent them). 
In my example above, the sub-nodes 2 & 3 only represent two yz-faces ( two parallel faces of the cube) and leave all the others behind. Shouldn't there be at least a third cube filling the void space between these two ultra-thin-plane-AABBs? 

To be honest, I expected the algorithm to produce only the one tree-node at the top without any sub-nodes because one box is the perfect representation of the given vertices and  faces. 
Also there are only 8 Vertices / 6 faces. Apparently these numbers are far away from the 32 items needed to split a node.

**Comment by dengwirda** [comment]
The `aabb-tree` presented here is not a `leaf-only` structure - there can be items indexed at higher levels of the tree. In your case, the tree has two levels (i.e. a root and two leaf nodes). The six faces of the cube are indexed between these three nodes.

There are (I think) good reasons to allow objects to be indexed by non-leaf nodes - if the collection contains 'long' items that would be hard to categorise amongst the small leaf nodes of a tree, it can be more efficient to allow these objects to reside at higher levels (i.e. inside larger tree nodes). The implementation provided here does this, though the approach used is just a heuristic.

Definitely the tree invariants are respected throughout - the children of each node are completely enclosed by the convex hull of the parent.

I agree that a better tree would comprise of just a single node in this case. The tree building algorithm used here is a heuristic, so non-optimal configurations can be generated. That said, the method appears to work reasonably well on complex inputs in practice, and hasn't produced invalid output in this case.

I'm happy to continue this conversation, though if there's no specific 'issue' involved it might be best to move it to email.

**Comment by TheBlune** [comment]
Thanks for your elaborate response. I would be happy to continue this and am closing this issue now.
